import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import FuckingHeader from "@/components/FuckingHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${inter.className} overflow-y-auto overflow-x-hidden`}>
        <FuckingHeader />
        {children}
      </body>
    </html>
  );
}
