import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import FlyingHeader from "@/components/FlyingHeader";
import kalameh from "@/font/kalameh";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fa" dir="rtl" className="dark">
      <body
        className={`${kalameh.className} overflow-y-auto overflow-x-hidden bg-cover bg-center bg-no-repeat`}
        style={{
          backgroundImage: 'url("/background.webp")',
        }}
      >
        <FlyingHeader />
        {children}
      </body>
    </html>
  );
}
